# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Release

on:
  push:
    branches: [ "main" ]

jobs:
  release:
    # 运行环境
    runs-on: ubuntu-latest
    permissions:
      contents: write
      steps:
        - uses: actions/checkout@v2
        - uses: ncipollo/release-action@v1
          with:
            artifacts: "fox.md"
            bodyFile: "body.md"
            token: ${{ secrets.RELEASE_TOKEN }}
